COPY (
	SELECT
		facilities.uid,
		facilities.hash,
		facilities.idold,
		array_to_string(facilities.idagency,',') AS idagency,
		facilities.facilityname,
		facilities.addressnumber,
		facilities.streetname,
		facilities.address,
		facilities.city,
		facilities.borough,
		facilities.boroughcode,
		facilities.zipcode,
		facilities.latitude,
		facilities.longitude,
		facilities.xcoord,
		facilities.ycoord,
		array_to_string(facilities.bin,',') AS bin,
		array_to_string(facilities.bbl,',') AS bbl,
		facilities.communityboard,
		facilities.councildistrict,
		facilities.censustract,
		facilities.nta,
		facilities.domain,
		facilities.facilitygroup,
		facilities.facilitysubgroup,
		facilities.facilitytype,
		array_to_string(facilities.capacity,',') AS capacity,
		array_to_string(facilities.utilization,',') AS utilization,
		array_to_string(facilities.capacitytype,',') AS capacitytype,
		array_to_string(facilities.utilizationrate,',') AS utilizationrate,
		array_to_string(facilities.area,',') AS area,
		array_to_string(facilities.areatype,',') AS areatype,
		facilities.propertytype,
		facilities.operatortype,
		facilities.operatorname,
		facilities.operatorabbrev,
		array_to_string(facilities.oversightlevel,',') AS oversightlevel,
		-- array_to_string(facilities.oversighttype,',') AS oversighttype,
		array_to_string(facilities.oversightagency,',') AS oversightagency,
		array_to_string(facilities.oversightabbrev,',') AS oversightabbrev,
		array_to_string(facilities.agencysource,',') AS agencysource,
		array_to_string(facilities.sourcedatasetname,',') AS sourcedatasetname,
		array_to_string(facilities.linkdata,',') AS linkdata,
		array_to_string(facilities.datesourceupdated,',') AS datesourceupdated,
		facilities.processingflag,
		-- facilities.agencyclass1,
		-- facilities.agencyclass2,
		-- facilities.colpusetype,
		-- facilities.dateactive,
		-- facilities.dateinactive,
		-- facilities.inactivestatus,
		-- array_to_string(facilities.tags,','),
		-- facilities.notes,
		-- array_to_string(facilities.datesourcereceived,','),
		-- facilities.datecreated,
		-- facilities.dateedited,
		-- facilities.creator,
		-- facilities.editor,
		-- array_to_string(facilities.linkdownload,','),
		-- array_to_string(facilities.datatype,','),
		-- array_to_string(facilities.refreshmeans,','),
		-- array_to_string(facilities.refreshfrequency,','),
		array_to_string(facilities.pgtable,',') AS pgtable,
		array_to_string(facilities.uid_merged,',') AS uid_merged,
		array_to_string(facilities.hash_merged,',') AS hash_merged,
		array_to_string(facilities.idagency_merged,',') AS idagency_merged,
		-- facilities.buildingid,
		-- facilities.buildingname,
		-- facilities.schoolorganizationlevel,
		-- facilities.children,
		-- facilities.youth,
		-- facilities.senior,
		-- facilities.family,
		-- facilities.disabilities,
		-- facilities.dropouts,
		-- facilities.unemployed,
		-- facilities.homeless,
		-- facilities.immigrants,
		-- facilities.groupquarters,
		facilities.geom
	FROM
		facilities,
		dcp_boroboundaries_wi
	WHERE
		facilities.geom IS NOT NULL
		AND ST_Intersects (facilities.geom, dcp_boroboundaries_wi.geom)
	ORDER BY
		-- domain, facilitygroup, facilitysubgroup, facilitytype
		RANDOM()
) TO '/Users/hannahbkates/Desktop/facilities.csv' WITH CSV DELIMITER ',' HEADER;