DROP TABLE IF EXISTS facilities;
CREATE TABLE facilities (
-- ids
guid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
hash text,
id text,
idold text,
idagency text ARRAY,
--name
facilityname text,
--location information
addressnumber text,
streetname text,
address text,
city text,
borough text,
boroughcode smallint,
zipcode integer,
-- spatial joins to polygons
bbl text ARRAY,
bin text ARRAY,
parkid text,
xcoord double precision,
ycoord double precision,
latitude double precision,
longitude double precision,
-- classification
facilitytype text,
domain text,
facilitygroup text,
facilitysubgroup text,
agencyclass1 text,
agencyclass2 text,
colpusetype text,
-- size
capacity double precision,
utilization double precision,
capacitytype text,
utilizationrate double precision,
area double precision,
areatype text,
servicearea text,
-- operator and agency information
operatortype text,
operatorname text,
operatorabbrev text,
oversightagency text ARRAY,
oversightabbrev text ARRAY,
-- information on when the facility opened/closed and tags classifing the facility
dateactive date,
dateinactive date,
inactivestatus boolean,
tags text ARRAY,
-- information to be tracked by the data admin
notes text,
datesourcereceived date ARRAY,
datesourceupdated date ARRAY,
datecreated date,
dateedited date,
creator text,
editor text,
geom geometry,
pgtable text ARRAY,
agencysource text ARRAY,
sourcedatasetname text ARRAY,
linkdata text ARRAY,
linkdownload text ARRAY,
datatype text ARRAY,
refreshmeans text ARRAY,
refreshfrequency text ARRAY,
processingflag text,
-- details on duplicate records merged into the primary record
guid_merged text ARRAY,
hash_merged text ARRAY,
idagency_merged text ARRAY,
-- attributes specific to schools
buildingid text,
buildingname text,
schoolorganizationlevel text,
-- served populations
children boolean,
youth boolean,
senior boolean,
family boolean,
disabilities boolean,
dropouts boolean,
unemployed boolean,
homeless boolean,
immigrants boolean,
-- miscellaneous
groupquarters boolean
)