DELETE FROM facilities
WHERE
	facilitysubgroup = 'Shelters and Transitional Housing'
	OR facilitytype = 'Family Foster Care'
	OR facilitytype = 'Residential Care'
	OR facilitytype = 'Residential Care Services '
	OR facilitytype = 'Specialized FFC: Children Who Have Been Sexually Exploited'
	OR facilitytype = 'Specialized FFC: Children With Special Medical Needs, Including HIV and/or AIDS'
	OR facilitytype = 'Specialized FFC: Children with Mental Retardation, Developmental Delays, and/or Developmental Disabilities'
	OR facilitytype = 'Specialized FFC: Rapid Intervention Teams'
	OR facilitytype = 'Specialized FFC: Treatment FFC for Children With Moderate to Severe Emotional and/or Behavioral Disorders'
	OR facilitytype = 'Specialized NSP: Youth with Fire Setting Behaviors'
	OR facilitytype = 'Specialized NSP: Youth with MR/DD'
	OR facilitytype = 'Specialized PC: Families with Children Who Have Been Sexually Exploited'
	OR facilitytype = 'Specialized PC: Families with Children or Parents Who Are Deaf/Hearing Impaired'
	OR facilitytype = 'Specialized PC: Family Treatment/Rehabilitation'
	OR facilitytype = 'Specialized PC: Family Treatment/Rehabilitation'
	OR facilitytype = 'Specialized PC: Special Medical and Developmental Preventive Program'
	OR facilitytype = 'Court Based Programs'
	OR facilitytype = 'Court Based Programs'
	OR facilitytype = 'Crime Victim Advocate Program'
	OR facilitytype = 'Crime Victims Services'
	OR facilitytype = 'AIDS: Counseling, Meals, and Other Services'
	OR facilitytype = 'AIDS: Non-Emergency Congregate Housing'
	OR facilitytype = 'AIDS: Permanent Congregate Housing'
	OR facilitytype = 'HIV/AIDS Services Administration'
	OR facilitytype = 'HIV/AIDS Services Administration'
	OR facilitytype = 'Limited-Secure Placement'
	OR facilitytype LIKE '%Non-Secure%'
	OR facilitytype LIKE '%Non-secure%'
	OR facilitytype LIKE '%NSP%'
	OR facilityname LIKE '%Non-secure%'
	OR facilityname LIKE '%Non-Secure%'
	OR facilityname LIKE '%NSP%'
	OR facilityname LIKE '%NSD%'
	OR facilityname LIKE '%Nsd%'
	OR facilityname LIKE '%Nsp%'